CREATE DATABASE AdvisorLegacy

GO
USE AdvisorLegacy

GO
CREATE TABLE [SINACOR_ADVISOR]
(
   [ID]	INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   [SINACOR_NAME] VARCHAR(60) NOT NULL,
   [SINACOR_CODE] int not null
)
GO
CREATE TABLE [ADVISOR_CLIENT_ACCOUNT]
(
   [CLIENT_ID]	INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   [SINACOR_ADVISOR_ID] INT NOT NULL,
   [ACCOUNT_ID]	INT NOT NULL,
   [ENABLED] BIT NOT NULL,
   [REGISTER_DATE] DATETIME NOT NULL, 
   [UPDATE_DATE] DATETIME null
)
GO
ALTER TABLE [ADVISOR_CLIENT_ACCOUNT] ADD CONSTRAINT [FK_SINACOR_ADVISOR] FOREIGN KEY ([SINACOR_ADVISOR_ID]) REFERENCES [SINACOR_ADVISOR]([ID])

insert into sinacor_advisor values ('Digital', '299')
insert into sinacor_advisor values ('Lopes', '300');