insert into ADVISOR_CLIENT_ACCOUNT values (1,405060,1,GETDATE(),null);
UPDATE ADVISOR_CLIENT_ACCOUNT SET SINACOR_ADVISOR_ID = 2, UPDATE_DATE = GETDATE() WHERE ACCOUNT_ID = 405060; 
delete from ADVISOR_CLIENT_ACCOUNT WHERE ACCOUNT_ID = 405060;

select * from cdc.dbo_ADVISOR_ClIENT_ACCOUNT_CT